class testdata:
    user_signup_url = "https://develop.d1b6r88mu92xay.amplifyapp.com/auth/signup"
    user_login_url= "https://develop.d1b6r88mu92xay.amplifyapp.com/auth/login"
    merchant_login_url= "https://develop.dc4234a3ywtax.amplifyapp.com/login/"
    merchant_signup_url= "https://develop.dc4234a3ywtax.amplifyapp.com/signup/"
    admin_app_url=""
    user_login_email= "farhaanuser3@yopmail.com"
    user_signup_email= "farhaanuser22@yopmail.com"
    user_password= "Farhan@1234"
    confirm_password= "Farhan@1234"
    merchant_login_email= "Farhanmerchant@yopmail.com"
    merchant_signup_email= "Farhanmerchant@yopmail.com"
    merchant_firstname= "Farhan"
    merchant_lastname= "Merchant"
    merchant_password= "Farhan@1234"
